import { Component, OnInit } from '@angular/core';
import {TimeLineInf} from '../time-line/timeline-inf';

@Component({
  selector: 'app-nuestra-historia',
  templateUrl: './nuestra-historia.component.html',
  styleUrls: ['./nuestra-historia.component.css']
})
export class NuestraHistoriaComponent implements OnInit {

timeline:TimeLineInf[] = [
 new TimeLineInf("../assets/timeline/Nuestra historia/Icono Rhino.png","Nacimiento NURBS", "01/01/1946",
 "Francia. Renault y Citroen contratan a los Ingenieros Pierre Bezier y Paul de Casteljau quienes son los pioneros en el desarrollo de las matemáticas para describir geometrías complejas, conocido actualmente como NURBS – B-Spllines Racionales No Uniformes.","http://assets.voxel3d.net/timeLine/1.jpg"),
 new TimeLineInf("../assets/timeline/Nuestra historia/Icono Rhino.png","Nace Robert McNeel & Associates", "01/01/1980", "Robert McNeel funda Robert McNeel & Associates. Se dedica a desarrollar software contable para compañías de ingeniería y arquitectura.","http://assets.voxel3d.net/timeLine/2.jpg"),
 new TimeLineInf("../assets/timeline/Nuestra historia/Icono Voxel.png","Acercamiento al mundo CAD por parte de Leonardo Velasco", "01/01/1984", "Leonardo Velasco conoce la primera versión de AutoCAD 2.0 que llega a Colombia, e inicia la aplicación del uso de sistemas CAD en sus proyectos académicos de bachillerato, en el Instituto Técnico Central, antigua Escuela de Artes y Oficios de Santa Fe de Bogotá.","http://assets.voxel3d.net/timeLine/3.jpg"),
 new TimeLineInf("../assets/timeline/Nuestra historia/Icono Rhino.png","Primeros desarrollos de McNeel", "01/01/1985", "McNeel se convierte en distribuidor y centro de capacitacion de Autocad. Inicia el proceso de desarrollo de Plugins para Autocad como Accurender","http://assets.voxel3d.net/timeLine/4.jpg"),
 new TimeLineInf("../assets/timeline/Nuestra historia/Icono Rhino.png","Modeladores NURBS y nacimiento de Sculptura", "01/05/1992", "Mayo: Applied Geometry (AG). AG contacta a McNeel para obtener ayuda en la integración de su AGLib, biblioteca de geometría NURBS, en AutoCAD. Julio: McNeel desarrolló un prototipo de la aplicación en AutoCAD después de 3 días de trabajo Noviembre:  McNeel y AG llegan a un acuerdo para desarrollar AccuModel, Plugin de modelado NURBS para AutoCAD. McNeel contrata a Michael Gibson como pasante. Gibson crea Sculptura, un modelador de malla que desarrollo como un proyecto académico.","http://assets.voxel3d.net/timeLine/5.jpg"),
 new TimeLineInf("../assets/timeline/Nuestra historia/Icono Rhino.png","Nacimiento de Rhinoceros", "01/03/1993", "Marzo: Sculptura es lanzado al mercado. el mismo año, McNeel asume la iniciativa en el desarrollo de AccuModel. Julio: Primer prototipo de Sculptura 2.0 listo para NURBS. Noviembre: El desarrollo de Sculptura 2 recibe el nombre clave de Rhinoceros.","http://assets.voxel3d.net/timeLine/6.jpg"),
 new TimeLineInf("../assets/timeline/Nuestra historia/Icono Rhino.png","Pruebas con Beta de Rhinoceros 1.0", "03/03/1993", "Bogotá 1993 – 1996:  Se desarrollan las primeras cuatro versiones del Salón de Diseño Industrial de la Universidad Nacional de Colombia, en Bogotá. Leonardo Velasco, como monitor de carrera, incorporar el uso de sistemas CAD -Autocad y CorelDRAW- y crear standares para la presentación de los proyectos de la exposición en el Museo Leopoldo Rother. En 1996, Leonardo conoce y trabaja la primera versión Beta de Rhinoceros 1.0, publicada en CD´s de revistas CAD.","http://assets.voxel3d.net/timeLine/7.jpg"),
 new TimeLineInf("../assets/timeline/Nuestra historia/Icono Rhino.png","Se oficializa Rhinoceros", "01/01/1994", "En enero se logra un acuerdo entre McNeel y AG donde McNeel se licencia con el desarrollo AGLib de AG y AG, y  en abril la primera versión Beta pública de Rhino fue compartida en Graphic Alternative BBS. En Agosto, Sculptura es bautizado oficialmente como Rhinoceros después de que se determinó que no habría forma de resolver asuntos de marcas con AccuModel.","http://assets.voxel3d.net/timeLine/8.jpg"),
 new TimeLineInf("../assets/timeline/Nuestra historia/Icono Rhino.png","Silicon Graphics compra a Alias ​​", "01/03/1995", "En marzo McNeel provee a Alias ​​la primera instalación de tecnología geométrica. En junio Alias ​​es comprado por Silicon Graphics, en ese mismo mes, McNeel recibe su última actualización de AGLib.","http://assets.voxel3d.net/timeLine/9.jpg"),
 new TimeLineInf("../assets/timeline/Nuestra historia/Icono Rhino.png","50.000 Usuarios alcanzados", "01/05/1997", "En mayo McNeel decide que enfocarse en la versión para Windows. En septiembre se llega a 50000 usuarios de versiones beta de Rhinoceros sin inversiones de publicidad ni mercadeo.","http://assets.voxel3d.net/timeLine/10.jpg"),
 new TimeLineInf("../assets/timeline/Nuestra historia/Icono Rhino.png","Actualización de la Beta de Rhino 1.0", "01/11/1997", "En noviembre Leonardo Velasco recibe la actualización de la Beta de Rhino 1.0, de Robert McNeel & Associates.","http://assets.voxel3d.net/timeLine/11.jpg"),
 new TimeLineInf("../assets/timeline/Nuestra historia/Icono Rhino.png","Primer curso de Rhinoceros en Latinoamerica", "20/01/1998", "En octubre se realiza el primer curso de Rhinoceros en Latinoamerica (instalaciones de BITS Ltda en Medellin) dirigido por Jerry Hambly. Leonardo Velasco participa en ese evento para fortalecer las practicas realizadas con las versiones beta.","http://assets.voxel3d.net/timeLine/12.jpg"),
 new TimeLineInf("../assets/timeline/Nuestra historia/Icono Rhino.png","Lanzamiento de Rhinoceros 1.0", "01/07/1998", "En julio se llega a 100000 usuarios beta. En julio se anuncia el lanzamiento de Rhinoceros 1.0 para el mes octubre en SIGGRAPH, y en diciembre se completan 5000 licencias de Rhino a nivel mundial.  ","http://assets.voxel3d.net/timeLine/13.jpg"),
 new TimeLineInf("../assets/timeline/Nuestra historia/Icono Rhino.png","Primera reunión de distribuidores Europeos", "01/01/1999", "Enero Lanzamiento de la versión en idioma japones de Rhino 1.0, es liberada la primera versión beta pública de Rhino 1.1 y se realiza en Barcelona la primera reunión de distribuidores Europeos.","http://assets.voxel3d.net/timeLine/14.jpg"),
 new TimeLineInf("../assets/timeline/Nuestra historia/Icono Rhino.png","Capacitación de Rhinoceros en el SENA", "01/07/1999", "En Julio, el centro de calzado del SENA en Cúcuta contrata a Leonardo Velasco para la capacitación en manejo de Rhinoceros 1.0 y brazo digitaizador MicroScribe G2.","http://assets.voxel3d.net/timeLine/15.jpg"),
 new TimeLineInf("../assets/timeline/Nuestra historia/Icono Rhino.png","Primeras versiones beta públicas de Rhinoceros 2.0 liberadas", "01/08/2000", "En agosto se liberan las primeras versiones beta públicas de Rhinoceros 2.0 y Flamingo.","http://assets.voxel3d.net/timeLine/16.jpg"),
 new TimeLineInf("../assets/timeline/Nuestra historia/Icono Voxel.png","Umiplast usa Beta de Rhino 2.0.", "15/08/2000", "En agosto Umiplast contrata a Leonardo Velasco para realizar el modelado 3D de las figuras de los Royalitos. Se fabrican los moldes y se realiza la producción de mas de 50.000 moldes incluidos en las cajas de gelatina Royal en Colombia. Se usa la versión Beta de Rhino 2.0.","http://assets.voxel3d.net/timeLine/17.jpg"),
 new TimeLineInf("../assets/timeline/Nuestra historia/Icono Rhino.png","Lanzamiento de Rhinoceros 2.0", "01/07/2001", "En agosto se realiza el lanzamiento de Rhinoceros 2.0.","http://assets.voxel3d.net/timeLine/18.jpg"),
 new TimeLineInf("../assets/timeline/Nuestra historia/Icono Rhino.png","Lanzamiento de Rhinoceros 3.0", "01/11/2002", "En noviembre se realiza el lanzamiento de Rhinoceros 3.0.","http://assets.voxel3d.net/timeLine/19.jpg"),
 new TimeLineInf("../assets/timeline/Nuestra historia/Icono Voxel.png","Placa S.A. usa Rhinoceros 3.0", "01/01/2005", "Enero 2005 – Placa S.A. del grupo Chaid Neme, solicita a Leonardo Velasco sus servicios profesionales para el modelado del envase para Shell Helix y el desarrollo de envases para Gaseosas Glacial, Productos Propersa, Linea de Aseo Carulla y Saleros para Refisal. Todos los Proyectos se realizan con Rhinoceros 3.0 y se ilustran con Flamingo, el modelado se integra en el flujo de trabajo con Pro-E.","http://assets.voxel3d.net/timeLine/20.jpg"),
 new TimeLineInf("../assets/timeline/Nuestra historia/Icono Voxel.png","Experiencia junto a Industrias Plasticas GR", "15/01/2005", "Industrias Plasticas GR, inicia el proceso de producción de careta para soldador, ganadora del Premio de Innovación en Suiza en 2004. Leonardo Velasco realiza el modelado que se usa para integrarlo con SolidEdge para su fabricación precisa.","http://assets.voxel3d.net/timeLine/21.jpg"),
 new TimeLineInf("../assets/timeline/Nuestra historia/Icono Voxel.png","Nace VOXEL C&T", "01/07/2006", "En julio Fabio Jara, David Cardenas y Leonardo Velasco llegan al acuerdo para conformar una empresa dedicada a la distribución y entrenamiento de Rhino en Colombia. Se registra la Compañía VOXEL C&T.","http://assets.voxel3d.net/timeLine/22.jpg"),
 new TimeLineInf("../assets/timeline/Nuestra historia/Icono Rhino.png","Lanzamiento de Rhinoceros 4.0.", "01/02/2007", "En febrero se realiza el lanzamiento de Rhinoceros 4.0.","http://assets.voxel3d.net/timeLine/23.jpg"),
 new TimeLineInf("../assets/timeline/Nuestra historia/Icono Voxel.png","Primer Centro Autorizado de Capacitación en Rhinoceros en Bogotá", "01/07/2007", "En Julio Voxel es reconocida como el primer centro Autorizado de Capacitación en Rhinoceros por Robert McNeel & Associates, en Bogotá.","http://assets.voxel3d.net/timeLine/24.jpg"),
 new TimeLineInf("../assets/timeline/Nuestra historia/Icono Voxel.png","Capacitación con la DIMAR.", "01/01/2009", "La DIMAR, entidad adscrita al Ministerio de defensa del Gobierno Nacional, selecciona a Voxel como empresa para suministrar el software y realizar la capacitación para su departamento técnico.","http://assets.voxel3d.net/timeLine/25.jpg"),
 new TimeLineInf("../assets/timeline/Nuestra historia/Icono Voxel.png","Caso FINART", "01/02/2009", "El departamento de i+d de FINART solicita los servicios de Voxel para entrenar a los diseñadores digitales de joyería para lograr un optimo uso de los sistemas de prototipado SolidScape. Actualmente los diseñadores de FINART han sido estudiantes de Voxel.","http://assets.voxel3d.net/timeLine/26.jpg"),
 new TimeLineInf("../assets/timeline/Nuestra historia/Icono Voxel.png","Caso COTECMAR.", "01/01/2010", "lVoxel suministra el software y realiza la capacitación del departamento de Diseño e Investigación en los Astilleros de COTECMAR en Cartagena.","http://assets.voxel3d.net/timeLine/27.jpg"),
 new TimeLineInf("../assets/timeline/Nuestra historia/Icono Voxel.png","DISEÑA TU 3DM MUNDO: Universidad Jorge Tadeo Lozano","03/01/2010", "Voxel gestiona el acuerdo entre Robert McNeel & Associates y la Universidad Jorge Tadeo Lozano en Bogotá y se realiza el evento DISEÑA TU 3DM MUNDO: Una semana de talleres y conferencias para render, diseño de producto, joyería y calzado.","http://assets.voxel3d.net/timeLine/28.jpg"),
 new TimeLineInf("../assets/timeline/Nuestra historia/Icono Voxel.png","Caso Coltoys", "01/03/2010", "Voxel realiza la integración de tecnologías y el entrenamiento para el desarrollo de juguetería en Coltoys.","http://assets.voxel3d.net/timeLine/29.jpg"),
 new TimeLineInf("../assets/timeline/Nuestra historia/Icono Voxel.png","Apertura de pasantías universitarias", "01/06/2010", "Voxel recibe pasantes de los programas de Diseño Industrial, Arquitectura e Ingeniería de Sistemas, de universidades de primer nivel como la pontificia Universidad Javeriana, la Universidad Autónoma de Colombia, la Universidad Piloto y la Universidad El Bosque.","http://assets.voxel3d.net/timeLine/30.jpg"),
 new TimeLineInf("../assets/timeline/Nuestra historia/Icono Voxel.png","Caso Universidad Nacional de Colombia", "01/03/2011", "En el diplomado de Arquitecturas Plásticas, dentro del Marco de la Maestría en Construcción de la Universidad Nacional de Colombia – Sede Bogotá – Voxel suministra los docentes para el entrenamiento en Rhinoceros, Grasshopper y sistemas CAM.","http://assets.voxel3d.net/timeLine/31.jpg"),
 new TimeLineInf("../assets/timeline/Nuestra historia/Icono Voxel.png","Caso Hunter Douglas", "01/01/2012", "Hunter Douglas de Colombia contacta a Voxel para realizar el entrenamiento en Rhinoceros y Grasshopper para sus departamentos de diseño, ingeniería, producción, ventas y costos, y como resultado el desarrollo nuevos productos realizados en sistemas CNC, basados en técnicas de modelado 3d y diseño generativo.","http://assets.voxel3d.net/timeLine/32.jpg"),
 new TimeLineInf("../assets/timeline/Nuestra historia/Icono Voxel.png","Caso Universidad de los Andes", "01/02/2012", "La Universidad de los Andes contrata a Voxel para realizar el entrenamiento de sus profesores del departamento de Diseño en Rhinoceros y Grasshopper.","http://assets.voxel3d.net/timeLine/33.jpg"),
 new TimeLineInf("../assets/timeline/Nuestra historia/Icono Rhino.png","Lanzamiento de Rhinoceros 5.0.", "01/10/2012", "En octubre se realiza el lanzamiento de Rhinoceros 5.0.","http://assets.voxel3d.net/timeLine/34.jpg"),
 new TimeLineInf("../assets/timeline/Nuestra historia/Icono Voxel.png","Voxel dentro de las empresas más innovadoras segun INNPULSA", "01/01/2014", "Voxel es seleccionada como finalista en el concurso INNPULSA, del Ministerio de Industria, Bancoldex y Presidencia de la República, como una de las empresas más innovadoras en procesos, por la transferencia de tecnología y el impacto positivo que hemos generado en el gremio de Joyeros en el Departamento de Santander.","http://assets.voxel3d.net/timeLine/35.jpg"),
 new TimeLineInf("../assets/timeline/Nuestra historia/Icono Voxel.png","Capacitación en el SENA", "01/02/2014", "Voxel es la entidad seleccionada por el SENA para recibir el entrenamiento de sus instructores de Rhinoceros para Joyería a nivel nacional.","http://assets.voxel3d.net/timeLine/36.jpg")
];

  constructor() { }

  ngOnInit() {
  }

}
